/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Accounts {
  balance: number;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  institutionId: string | null;
  name: string;
  note: string | null;
  openedAt: Generated<Timestamp>;
  openingBalance: number;
  status: Generated<string>;
  type: string;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface AiUsage {
  count: Generated<number>;
  month: string;
  userId: string;
}

export interface CategoryGroups {
  colorName: string;
  createdAt: Generated<Timestamp>;
  iconName: string;
  id: Generated<string>;
  name: string;
  sortOrder: Generated<number>;
  status: Generated<string>;
  type: string;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface CategoryItems {
  createdAt: Generated<Timestamp>;
  groupId: string;
  iconName: string;
  id: Generated<string>;
  name: string;
  sortOrder: Generated<number>;
  status: Generated<string>;
  type: string;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface Contacts {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  initials: string;
  name: string;
  note: string | null;
  phone: string | null;
  relationship: string | null;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface DebtOperations {
  createdAt: Generated<Timestamp>;
  fingerprint: string;
  id: string;
  userId: string;
}

export interface DebtPayments {
  accountId: string;
  amount: number;
  createdAt: Generated<Timestamp>;
  debtId: string;
  id: Generated<string>;
  note: string | null;
  paidAt: string;
  paidTime: string;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface Debts {
  accountId: string | null;
  amount: number;
  contactId: string;
  createdAt: Generated<Timestamp>;
  direction: string;
  dueAt: string | null;
  id: Generated<string>;
  interestPeriod: string | null;
  interestRate: number | null;
  note: string | null;
  recordedAt: string;
  recordingMode: Generated<string>;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface MissionRewards {
  claimedAt: Generated<Timestamp>;
  credits: number;
  mission: string;
  userId: string;
}

export interface NotificationBrowsers {
  deviceId: string | null;
  id: string;
  sessionId: string;
  updatedAt: Generated<Timestamp>;
  userId: string | null;
}

export interface NotificationLogDevices {
  attempts: Generated<number>;
  date: string;
  deviceId: string;
  errorCode: string | null;
  retryAt: Timestamp | null;
  status: string;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface NotificationLogs {
  attemptId: string | null;
  createdAt: Generated<Timestamp>;
  date: string;
  leaseUntil: Timestamp | null;
  messageBody: string;
  messageTitle: string;
  status: string;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface NotificationSettings {
  dailyReminderTime: Generated<string>;
  nextReminderAt: Timestamp | null;
  notificationsEnabled: Generated<boolean>;
  timeZone: Generated<string>;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface Payments {
  amount: number;
  checkoutUrl: string | null;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  orderCode: Generated<number>;
  paidAt: Timestamp | null;
  paymentLinkId: string | null;
  period: string;
  reference: string | null;
  status: Generated<string>;
  subscriptionId: string | null;
  userId: string;
}

export interface PushDevices {
  browserId: string;
  createdAt: Generated<Timestamp>;
  fid: string;
  id: string;
  name: string;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface Subscriptions {
  amount: Generated<number>;
  createdAt: Generated<Timestamp>;
  endsAt: Timestamp;
  grantedBy: string;
  id: Generated<string>;
  note: string | null;
  plan: string;
  revokedAt: Timestamp | null;
  startsAt: Timestamp;
  userId: string;
}

export interface Transactions {
  accountId: string | null;
  amount: number;
  categoryItemId: string | null;
  createdAt: Generated<Timestamp>;
  debtId: string | null;
  fee: Generated<number>;
  fromAccountId: string | null;
  id: Generated<string>;
  kind: string;
  note: string | null;
  occurredAt: Timestamp;
  toAccountId: string | null;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface Users {
  aiCredits: Generated<number>;
  categoriesInitializedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  id: string;
  onboardingSeenAt: Timestamp | null;
}

export interface DB {
  accounts: Accounts;
  aiUsage: AiUsage;
  categoryGroups: CategoryGroups;
  categoryItems: CategoryItems;
  contacts: Contacts;
  debtOperations: DebtOperations;
  debtPayments: DebtPayments;
  debts: Debts;
  missionRewards: MissionRewards;
  notificationBrowsers: NotificationBrowsers;
  notificationLogDevices: NotificationLogDevices;
  notificationLogs: NotificationLogs;
  notificationSettings: NotificationSettings;
  payments: Payments;
  pushDevices: PushDevices;
  subscriptions: Subscriptions;
  transactions: Transactions;
  users: Users;
}
