import type { LucideIcon } from "lucide-react"
import {
  AppleIcon,
  BabyIcon,
  BadgeDollarSignIcon,
  BadgePercentIcon,
  BanknoteIcon,
  BedDoubleIcon,
  BikeIcon,
  BitcoinIcon,
  BookOpenIcon,
  BriefcaseBusinessIcon,
  Building2Icon,
  BusFrontIcon,
  CakeSliceIcon,
  CarFrontIcon,
  CatIcon,
  ChartNoAxesCombinedIcon,
  CircleDollarSignIcon,
  CircleParkingIcon,
  ClapperboardIcon,
  ClockIcon,
  CloudSunIcon,
  CoffeeIcon,
  CoinsIcon,
  CreditCardIcon,
  DogIcon,
  DumbbellIcon,
  FactoryIcon,
  FilmIcon,
  FuelIcon,
  Gamepad2Icon,
  GiftIcon,
  GraduationCapIcon,
  HamburgerIcon,
  HandCoinsIcon,
  HeartPulseIcon,
  HospitalIcon,
  HotelIcon,
  HouseIcon,
  LandmarkIcon,
  LaptopIcon,
  LightbulbIcon,
  MedalIcon,
  MonitorSmartphoneIcon,
  MusicIcon,
  PackageIcon,
  PawPrintIcon,
  PhoneIcon,
  PiggyBankIcon,
  PizzaIcon,
  PlaneIcon,
  PopcornIcon,
  ReceiptTextIcon,
  SaladIcon,
  SandwichIcon,
  SchoolIcon,
  ShirtIcon,
  ShoppingBagIcon,
  ShoppingBasketIcon,
  ShoppingCartIcon,
  SmartphoneIcon,
  SoupIcon,
  SparklesIcon,
  StethoscopeIcon,
  StoreIcon,
  TicketIcon,
  TrainFrontIcon,
  TrophyIcon,
  TruckIcon,
  TvIcon,
  UmbrellaIcon,
  UtensilsIcon,
  WalletCardsIcon,
  WifiIcon,
  WineIcon,
  WrenchIcon,
  ZapIcon,
} from "lucide-react"

export const categoryIconRegistry = {
  apple: AppleIcon,
  baby: BabyIcon,
  "badge-dollar": BadgeDollarSignIcon,
  "badge-percent": BadgePercentIcon,
  banknote: BanknoteIcon,
  bed: BedDoubleIcon,
  bike: BikeIcon,
  bitcoin: BitcoinIcon,
  book: BookOpenIcon,
  briefcase: BriefcaseBusinessIcon,
  building: Building2Icon,
  bus: BusFrontIcon,
  cake: CakeSliceIcon,
  car: CarFrontIcon,
  cat: CatIcon,
  chart: ChartNoAxesCombinedIcon,
  "circle-dollar": CircleDollarSignIcon,
  parking: CircleParkingIcon,
  clapperboard: ClapperboardIcon,
  clock: ClockIcon,
  weather: CloudSunIcon,
  coffee: CoffeeIcon,
  coins: CoinsIcon,
  "credit-card": CreditCardIcon,
  dog: DogIcon,
  dumbbell: DumbbellIcon,
  factory: FactoryIcon,
  film: FilmIcon,
  fuel: FuelIcon,
  gamepad: Gamepad2Icon,
  gift: GiftIcon,
  graduation: GraduationCapIcon,
  hamburger: HamburgerIcon,
  "hand-coins": HandCoinsIcon,
  heart: HeartPulseIcon,
  hospital: HospitalIcon,
  hotel: HotelIcon,
  house: HouseIcon,
  landmark: LandmarkIcon,
  laptop: LaptopIcon,
  lightbulb: LightbulbIcon,
  medal: MedalIcon,
  devices: MonitorSmartphoneIcon,
  music: MusicIcon,
  package: PackageIcon,
  paw: PawPrintIcon,
  phone: PhoneIcon,
  "piggy-bank": PiggyBankIcon,
  pizza: PizzaIcon,
  plane: PlaneIcon,
  popcorn: PopcornIcon,
  receipt: ReceiptTextIcon,
  salad: SaladIcon,
  sandwich: SandwichIcon,
  school: SchoolIcon,
  shirt: ShirtIcon,
  "shopping-bag": ShoppingBagIcon,
  "shopping-basket": ShoppingBasketIcon,
  "shopping-cart": ShoppingCartIcon,
  smartphone: SmartphoneIcon,
  soup: SoupIcon,
  sparkles: SparklesIcon,
  stethoscope: StethoscopeIcon,
  store: StoreIcon,
  ticket: TicketIcon,
  train: TrainFrontIcon,
  trophy: TrophyIcon,
  truck: TruckIcon,
  tv: TvIcon,
  umbrella: UmbrellaIcon,
  utensils: UtensilsIcon,
  wallet: WalletCardsIcon,
  wifi: WifiIcon,
  wine: WineIcon,
  wrench: WrenchIcon,
  zap: ZapIcon,
} as const satisfies Record<string, LucideIcon>

export type CategoryIconName = keyof typeof categoryIconRegistry

export const categoryIconOptions: Array<{
  name: CategoryIconName
  label: string
}> = [
  { name: "wallet", label: "Ví tiền" },
  { name: "banknote", label: "Tiền mặt" },
  { name: "coins", label: "Tiền xu" },
  { name: "credit-card", label: "Thẻ tín dụng" },
  { name: "circle-dollar", label: "Tài chính" },
  { name: "hand-coins", label: "Thu nhập" },
  { name: "piggy-bank", label: "Tiết kiệm" },
  { name: "badge-dollar", label: "Thanh toán" },
  { name: "badge-percent", label: "Khuyến mãi" },
  { name: "bitcoin", label: "Tiền mã hoá" },
  { name: "landmark", label: "Ngân hàng" },
  { name: "chart", label: "Đầu tư" },
  { name: "briefcase", label: "Công việc" },
  { name: "factory", label: "Sản xuất" },
  { name: "store", label: "Cửa hàng" },
  { name: "shopping-bag", label: "Mua sắm" },
  { name: "shopping-basket", label: "Đi chợ" },
  { name: "shopping-cart", label: "Giỏ hàng" },
  { name: "package", label: "Hàng hoá" },
  { name: "shirt", label: "Quần áo" },
  { name: "utensils", label: "Ăn uống" },
  { name: "coffee", label: "Cà phê" },
  { name: "soup", label: "Món nước" },
  { name: "pizza", label: "Pizza" },
  { name: "hamburger", label: "Đồ ăn nhanh" },
  { name: "sandwich", label: "Bánh mì" },
  { name: "salad", label: "Rau củ" },
  { name: "apple", label: "Trái cây" },
  { name: "cake", label: "Bánh ngọt" },
  { name: "wine", label: "Đồ uống" },
  { name: "house", label: "Nhà cửa" },
  { name: "building", label: "Toà nhà" },
  { name: "bed", label: "Phòng ngủ" },
  { name: "lightbulb", label: "Điện" },
  { name: "wifi", label: "Internet" },
  { name: "wrench", label: "Sửa chữa" },
  { name: "zap", label: "Năng lượng" },
  { name: "car", label: "Ô tô" },
  { name: "bus", label: "Xe buýt" },
  { name: "bike", label: "Xe đạp" },
  { name: "train", label: "Tàu hoả" },
  { name: "truck", label: "Vận chuyển" },
  { name: "fuel", label: "Nhiên liệu" },
  { name: "parking", label: "Đỗ xe" },
  { name: "plane", label: "Máy bay" },
  { name: "hotel", label: "Khách sạn" },
  { name: "umbrella", label: "Kỳ nghỉ" },
  { name: "laptop", label: "Máy tính" },
  { name: "smartphone", label: "Điện thoại" },
  { name: "phone", label: "Liên lạc" },
  { name: "devices", label: "Thiết bị" },
  { name: "gift", label: "Quà tặng" },
  { name: "sparkles", label: "Làm đẹp" },
  { name: "heart", label: "Sức khoẻ" },
  { name: "stethoscope", label: "Khám bệnh" },
  { name: "hospital", label: "Bệnh viện" },
  { name: "dumbbell", label: "Thể thao" },
  { name: "school", label: "Trường học" },
  { name: "graduation", label: "Giáo dục" },
  { name: "book", label: "Sách" },
  { name: "film", label: "Phim ảnh" },
  { name: "clapperboard", label: "Điện ảnh" },
  { name: "tv", label: "Truyền hình" },
  { name: "gamepad", label: "Trò chơi" },
  { name: "music", label: "Âm nhạc" },
  { name: "ticket", label: "Sự kiện" },
  { name: "popcorn", label: "Giải trí" },
  { name: "trophy", label: "Giải thưởng" },
  { name: "medal", label: "Thành tích" },
  { name: "baby", label: "Trẻ em" },
  { name: "paw", label: "Thú cưng" },
  { name: "cat", label: "Mèo" },
  { name: "dog", label: "Chó" },
  { name: "clock", label: "Thời gian" },
  { name: "weather", label: "Thời tiết" },
  { name: "receipt", label: "Hoá đơn" },
]
