import type { LucideIcon } from "lucide-react"
import {
  AppleIcon,
  BabyIcon,
  BadgeDollarSignIcon,
  BadgePercentIcon,
  BanknoteIcon,
  BedDoubleIcon,
  BikeIcon,
  BitcoinIcon,
  BookOpenIcon,
  BriefcaseBusinessIcon,
  Building2Icon,
  BusFrontIcon,
  CakeSliceIcon,
  CarFrontIcon,
  CatIcon,
  ChartNoAxesCombinedIcon,
  CircleDollarSignIcon,
  CircleParkingIcon,
  ClapperboardIcon,
  ClockIcon,
  CloudSunIcon,
  CoffeeIcon,
  CoinsIcon,
  CreditCardIcon,
  DogIcon,
  DumbbellIcon,
  FactoryIcon,
  FilmIcon,
  FuelIcon,
  Gamepad2Icon,
  GiftIcon,
  GraduationCapIcon,
  HamburgerIcon,
  HandCoinsIcon,
  HeartPulseIcon,
  HospitalIcon,
  HotelIcon,
  HouseIcon,
  LandmarkIcon,
  LaptopIcon,
  LightbulbIcon,
  MedalIcon,
  MonitorSmartphoneIcon,
  MusicIcon,
  PackageIcon,
  PawPrintIcon,
  PhoneIcon,
  PiggyBankIcon,
  PizzaIcon,
  PlaneIcon,
  PopcornIcon,
  ReceiptTextIcon,
  SaladIcon,
  SandwichIcon,
  SchoolIcon,
  ShirtIcon,
  ShoppingBagIcon,
  ShoppingBasketIcon,
  ShoppingCartIcon,
  SmartphoneIcon,
  SoupIcon,
  SparklesIcon,
  StethoscopeIcon,
  StoreIcon,
  TicketIcon,
  TrainFrontIcon,
  TrophyIcon,
  TruckIcon,
  TvIcon,
  UmbrellaIcon,
  UtensilsIcon,
  WalletCardsIcon,
  WifiIcon,
  WineIcon,
  WrenchIcon,
  ZapIcon,
  AccessibilityIcon,
  ActivityIcon,
  AmbulanceIcon,
  ArmchairIcon,
  AwardIcon,
  BadgeCentIcon,
  BadgeCheckIcon,
  BadgeIndianRupeeIcon,
  BadgeJapaneseYenIcon,
  BaggageClaimIcon,
  BananaIcon,
  BandageIcon,
  BanknoteArrowDownIcon,
  BanknoteArrowUpIcon,
  BathIcon,
  BedSingleIcon,
  BeefIcon,
  BeerIcon,
  BoneIcon,
  BookMarkedIcon,
  BookOpenCheckIcon,
  BrainIcon,
  BusIcon,
  CableCarIcon,
  CakeIcon,
  CalculatorIcon,
  CandyIcon,
  CarTaxiFrontIcon,
  CaravanIcon,
  CarrotIcon,
  ChartColumnIcon,
  ChartPieIcon,
  ChartSplineIcon,
  ChefHatIcon,
  CherryIcon,
  CitrusIcon,
  CircleEuroIcon,
  CirclePoundSterlingIcon,
  ClipboardListIcon,
  CompassIcon,
  ContactIcon,
  CookieIcon,
  CookingPotIcon,
  CroissantIcon,
  CrossIcon,
  CrownIcon,
  CupSodaIcon,
  DessertIcon,
  DnaIcon,
  DollarSignIcon,
  DoorOpenIcon,
  DrillIcon,
  DrumstickIcon,
  EarIcon,
  EggIcon,
  EyeIcon,
  FanIcon,
  FenceIcon,
  FileTextIcon,
  FishIcon,
  FlaskConicalIcon,
  GlassesIcon,
  GrapeIcon,
  HammerIcon,
  HandHeartIcon,
  HandshakeIcon,
  HeartHandshakeIcon,
  HeartIcon,
  IceCreamBowlIcon,
  IceCreamConeIcon,
  KeyRoundIcon,
  LampDeskIcon,
  LanguagesIcon,
  LibraryIcon,
  LollipopIcon,
  LuggageIcon,
  MapPinIcon,
  MapPinnedIcon,
  MartiniIcon,
  MicrowaveIcon,
  MicroscopeIcon,
  MilkIcon,
  MotorbikeIcon,
  NavigationIcon,
  NotebookPenIcon,
  NutIcon,
  PaintRollerIcon,
  PartyPopperIcon,
  PenToolIcon,
  PencilRulerIcon,
  PercentIcon,
  PersonStandingIcon,
  PillIcon,
  PlaneLandingIcon,
  PlaneTakeoffIcon,
  PlugIcon,
  PresentationIcon,
  ReceiptIcon,
  RefrigeratorIcon,
  RocketIcon,
  RouteIcon,
  SailboatIcon,
  ScaleIcon,
  ShipIcon,
  ShowerHeadIcon,
  SmileIcon,
  SofaIcon,
  SyringeIcon,
  TestTubeIcon,
  ThermometerIcon,
  TractorIcon,
  TramFrontIcon,
  TrendingDownIcon,
  TrendingUpIcon,
  UserRoundCheckIcon,
  UserRoundIcon,
  UsersIcon,
  UtilityPoleIcon,
  VaultIcon,
  VeganIcon,
  WalletMinimalIcon,
  WarehouseIcon,
  WashingMachineIcon,
  WheatIcon,
} from "lucide-react"

export const categoryIconRegistry = {
  apple: AppleIcon,
  baby: BabyIcon,
  "badge-dollar": BadgeDollarSignIcon,
  "badge-percent": BadgePercentIcon,
  banknote: BanknoteIcon,
  bed: BedDoubleIcon,
  bike: BikeIcon,
  bitcoin: BitcoinIcon,
  book: BookOpenIcon,
  briefcase: BriefcaseBusinessIcon,
  building: Building2Icon,
  bus: BusFrontIcon,
  cake: CakeSliceIcon,
  car: CarFrontIcon,
  cat: CatIcon,
  chart: ChartNoAxesCombinedIcon,
  "circle-dollar": CircleDollarSignIcon,
  parking: CircleParkingIcon,
  clapperboard: ClapperboardIcon,
  clock: ClockIcon,
  weather: CloudSunIcon,
  coffee: CoffeeIcon,
  coins: CoinsIcon,
  "credit-card": CreditCardIcon,
  dog: DogIcon,
  dumbbell: DumbbellIcon,
  factory: FactoryIcon,
  film: FilmIcon,
  fuel: FuelIcon,
  gamepad: Gamepad2Icon,
  gift: GiftIcon,
  graduation: GraduationCapIcon,
  hamburger: HamburgerIcon,
  "hand-coins": HandCoinsIcon,
  heart: HeartPulseIcon,
  hospital: HospitalIcon,
  hotel: HotelIcon,
  house: HouseIcon,
  landmark: LandmarkIcon,
  laptop: LaptopIcon,
  lightbulb: LightbulbIcon,
  medal: MedalIcon,
  devices: MonitorSmartphoneIcon,
  music: MusicIcon,
  package: PackageIcon,
  paw: PawPrintIcon,
  phone: PhoneIcon,
  "piggy-bank": PiggyBankIcon,
  pizza: PizzaIcon,
  plane: PlaneIcon,
  popcorn: PopcornIcon,
  receipt: ReceiptTextIcon,
  salad: SaladIcon,
  sandwich: SandwichIcon,
  school: SchoolIcon,
  shirt: ShirtIcon,
  "shopping-bag": ShoppingBagIcon,
  "shopping-basket": ShoppingBasketIcon,
  "shopping-cart": ShoppingCartIcon,
  smartphone: SmartphoneIcon,
  soup: SoupIcon,
  sparkles: SparklesIcon,
  stethoscope: StethoscopeIcon,
  store: StoreIcon,
  ticket: TicketIcon,
  train: TrainFrontIcon,
  trophy: TrophyIcon,
  truck: TruckIcon,
  tv: TvIcon,
  umbrella: UmbrellaIcon,
  utensils: UtensilsIcon,
  wallet: WalletCardsIcon,
  wifi: WifiIcon,
  wine: WineIcon,
  wrench: WrenchIcon,
  zap: ZapIcon,
  accessibility: AccessibilityIcon,
  activity: ActivityIcon,
  ambulance: AmbulanceIcon,
  armchair: ArmchairIcon,
  award: AwardIcon,
  "badge-cent": BadgeCentIcon,
  "badge-check": BadgeCheckIcon,
  rupee: BadgeIndianRupeeIcon,
  yen: BadgeJapaneseYenIcon,
  baggage: BaggageClaimIcon,
  banana: BananaIcon,
  bandage: BandageIcon,
  "banknote-down": BanknoteArrowDownIcon,
  "banknote-up": BanknoteArrowUpIcon,
  bath: BathIcon,
  "bed-single": BedSingleIcon,
  beef: BeefIcon,
  beer: BeerIcon,
  bone: BoneIcon,
  "book-marked": BookMarkedIcon,
  "book-check": BookOpenCheckIcon,
  brain: BrainIcon,
  "bus-basic": BusIcon,
  "cable-car": CableCarIcon,
  "cake-basic": CakeIcon,
  calculator: CalculatorIcon,
  candy: CandyIcon,
  taxi: CarTaxiFrontIcon,
  caravan: CaravanIcon,
  carrot: CarrotIcon,
  "chart-column": ChartColumnIcon,
  "chart-pie": ChartPieIcon,
  "chart-spline": ChartSplineIcon,
  "chef-hat": ChefHatIcon,
  cherry: CherryIcon,
  citrus: CitrusIcon,
  euro: CircleEuroIcon,
  pound: CirclePoundSterlingIcon,
  clipboard: ClipboardListIcon,
  compass: CompassIcon,
  contact: ContactIcon,
  cookie: CookieIcon,
  "cooking-pot": CookingPotIcon,
  croissant: CroissantIcon,
  cross: CrossIcon,
  crown: CrownIcon,
  soda: CupSodaIcon,
  dessert: DessertIcon,
  dna: DnaIcon,
  dollar: DollarSignIcon,
  door: DoorOpenIcon,
  drill: DrillIcon,
  drumstick: DrumstickIcon,
  ear: EarIcon,
  egg: EggIcon,
  eye: EyeIcon,
  fan: FanIcon,
  fence: FenceIcon,
  "file-text": FileTextIcon,
  fish: FishIcon,
  flask: FlaskConicalIcon,
  glasses: GlassesIcon,
  grape: GrapeIcon,
  hammer: HammerIcon,
  "hand-heart": HandHeartIcon,
  handshake: HandshakeIcon,
  "heart-handshake": HeartHandshakeIcon,
  "heart-basic": HeartIcon,
  "ice-cream-bowl": IceCreamBowlIcon,
  "ice-cream-cone": IceCreamConeIcon,
  key: KeyRoundIcon,
  lamp: LampDeskIcon,
  languages: LanguagesIcon,
  library: LibraryIcon,
  lollipop: LollipopIcon,
  luggage: LuggageIcon,
  "map-pin": MapPinIcon,
  "map-pinned": MapPinnedIcon,
  martini: MartiniIcon,
  microwave: MicrowaveIcon,
  microscope: MicroscopeIcon,
  milk: MilkIcon,
  motorbike: MotorbikeIcon,
  navigation: NavigationIcon,
  notebook: NotebookPenIcon,
  nut: NutIcon,
  "paint-roller": PaintRollerIcon,
  party: PartyPopperIcon,
  "pen-tool": PenToolIcon,
  "pencil-ruler": PencilRulerIcon,
  percent: PercentIcon,
  person: PersonStandingIcon,
  pill: PillIcon,
  "plane-landing": PlaneLandingIcon,
  "plane-takeoff": PlaneTakeoffIcon,
  plug: PlugIcon,
  presentation: PresentationIcon,
  "receipt-basic": ReceiptIcon,
  refrigerator: RefrigeratorIcon,
  rocket: RocketIcon,
  route: RouteIcon,
  sailboat: SailboatIcon,
  scale: ScaleIcon,
  ship: ShipIcon,
  shower: ShowerHeadIcon,
  smile: SmileIcon,
  sofa: SofaIcon,
  syringe: SyringeIcon,
  "test-tube": TestTubeIcon,
  thermometer: ThermometerIcon,
  tractor: TractorIcon,
  tram: TramFrontIcon,
  "trending-down": TrendingDownIcon,
  "trending-up": TrendingUpIcon,
  "user-check": UserRoundCheckIcon,
  user: UserRoundIcon,
  users: UsersIcon,
  "utility-pole": UtilityPoleIcon,
  vault: VaultIcon,
  vegan: VeganIcon,
  "wallet-minimal": WalletMinimalIcon,
  warehouse: WarehouseIcon,
  "washing-machine": WashingMachineIcon,
  wheat: WheatIcon,
} as const satisfies Record<string, LucideIcon>

export type CategoryIconName = keyof typeof categoryIconRegistry

export const categoryIconOptions: Array<{
  name: CategoryIconName
  label: string
}> = [
  { name: "wallet", label: "Ví tiền" },
  { name: "banknote", label: "Tiền mặt" },
  { name: "coins", label: "Tiền xu" },
  { name: "credit-card", label: "Thẻ tín dụng" },
  { name: "circle-dollar", label: "Tài chính" },
  { name: "hand-coins", label: "Thu nhập" },
  { name: "piggy-bank", label: "Tiết kiệm" },
  { name: "badge-dollar", label: "Thanh toán" },
  { name: "badge-percent", label: "Khuyến mãi" },
  { name: "bitcoin", label: "Tiền mã hoá" },
  { name: "landmark", label: "Ngân hàng" },
  { name: "chart", label: "Đầu tư" },
  { name: "briefcase", label: "Công việc" },
  { name: "factory", label: "Sản xuất" },
  { name: "store", label: "Cửa hàng" },
  { name: "shopping-bag", label: "Mua sắm" },
  { name: "shopping-basket", label: "Đi chợ" },
  { name: "shopping-cart", label: "Giỏ hàng" },
  { name: "package", label: "Hàng hoá" },
  { name: "shirt", label: "Quần áo" },
  { name: "utensils", label: "Ăn uống" },
  { name: "coffee", label: "Cà phê" },
  { name: "soup", label: "Món nước" },
  { name: "pizza", label: "Pizza" },
  { name: "hamburger", label: "Đồ ăn nhanh" },
  { name: "sandwich", label: "Bánh mì" },
  { name: "salad", label: "Rau củ" },
  { name: "apple", label: "Trái cây" },
  { name: "cake", label: "Bánh ngọt" },
  { name: "wine", label: "Đồ uống" },
  { name: "house", label: "Nhà cửa" },
  { name: "building", label: "Toà nhà" },
  { name: "bed", label: "Phòng ngủ" },
  { name: "lightbulb", label: "Điện" },
  { name: "wifi", label: "Internet" },
  { name: "wrench", label: "Sửa chữa" },
  { name: "zap", label: "Năng lượng" },
  { name: "car", label: "Ô tô" },
  { name: "bus", label: "Xe buýt" },
  { name: "bike", label: "Xe đạp" },
  { name: "train", label: "Tàu hoả" },
  { name: "truck", label: "Vận chuyển" },
  { name: "fuel", label: "Nhiên liệu" },
  { name: "parking", label: "Đỗ xe" },
  { name: "plane", label: "Máy bay" },
  { name: "hotel", label: "Khách sạn" },
  { name: "umbrella", label: "Kỳ nghỉ" },
  { name: "laptop", label: "Máy tính" },
  { name: "smartphone", label: "Điện thoại" },
  { name: "phone", label: "Liên lạc" },
  { name: "devices", label: "Thiết bị" },
  { name: "gift", label: "Quà tặng" },
  { name: "sparkles", label: "Làm đẹp" },
  { name: "heart", label: "Sức khoẻ" },
  { name: "stethoscope", label: "Khám bệnh" },
  { name: "hospital", label: "Bệnh viện" },
  { name: "dumbbell", label: "Thể thao" },
  { name: "school", label: "Trường học" },
  { name: "graduation", label: "Giáo dục" },
  { name: "book", label: "Sách" },
  { name: "film", label: "Phim ảnh" },
  { name: "clapperboard", label: "Điện ảnh" },
  { name: "tv", label: "Truyền hình" },
  { name: "gamepad", label: "Trò chơi" },
  { name: "music", label: "Âm nhạc" },
  { name: "ticket", label: "Sự kiện" },
  { name: "popcorn", label: "Giải trí" },
  { name: "trophy", label: "Giải thưởng" },
  { name: "medal", label: "Thành tích" },
  { name: "baby", label: "Trẻ em" },
  { name: "paw", label: "Thú cưng" },
  { name: "cat", label: "Mèo" },
  { name: "dog", label: "Chó" },
  { name: "clock", label: "Thời gian" },
  { name: "weather", label: "Thời tiết" },
  { name: "receipt", label: "Hoá đơn" },
  { name: "calculator", label: "Máy tính" },
  { name: "chart-pie", label: "Biểu đồ tròn" },
  { name: "chart-column", label: "Biểu đồ cột" },
  { name: "chart-spline", label: "Biểu đồ tăng trưởng" },
  { name: "trending-up", label: "Tăng trưởng" },
  { name: "trending-down", label: "Sụt giảm" },
  { name: "handshake", label: "Hợp tác" },
  { name: "dollar", label: "Đô la" },
  { name: "percent", label: "Phần trăm" },
  { name: "badge-cent", label: "Tiền lẻ" },
  { name: "receipt-basic", label: "Biên lai" },
  { name: "pound", label: "Bảng Anh" },
  { name: "euro", label: "Euro" },
  { name: "banknote-up", label: "Tiền vào" },
  { name: "banknote-down", label: "Tiền ra" },
  { name: "scale", label: "Cân đối" },
  { name: "vault", label: "Két sắt" },
  { name: "wallet-minimal", label: "Ví nhỏ" },
  { name: "rupee", label: "Rupee" },
  { name: "yen", label: "Yên Nhật" },
  { name: "beef", label: "Thịt bò" },
  { name: "drumstick", label: "Thịt gà" },
  { name: "fish", label: "Cá" },
  { name: "egg", label: "Trứng" },
  { name: "milk", label: "Sữa" },
  { name: "cookie", label: "Bánh quy" },
  { name: "croissant", label: "Bánh sừng bò" },
  { name: "ice-cream-bowl", label: "Kem ly" },
  { name: "ice-cream-cone", label: "Kem ốc quế" },
  { name: "citrus", label: "Cam chanh" },
  { name: "cherry", label: "Anh đào" },
  { name: "grape", label: "Nho" },
  { name: "carrot", label: "Cà rốt" },
  { name: "wheat", label: "Ngũ cốc" },
  { name: "vegan", label: "Đồ chay" },
  { name: "cooking-pot", label: "Nấu ăn" },
  { name: "chef-hat", label: "Đầu bếp" },
  { name: "soda", label: "Nước ngọt" },
  { name: "martini", label: "Cocktail" },
  { name: "beer", label: "Bia" },
  { name: "dessert", label: "Tráng miệng" },
  { name: "candy", label: "Kẹo" },
  { name: "lollipop", label: "Kẹo mút" },
  { name: "nut", label: "Hạt" },
  { name: "banana", label: "Chuối" },
  { name: "motorbike", label: "Xe máy" },
  { name: "ship", label: "Tàu biển" },
  { name: "sailboat", label: "Thuyền buồm" },
  { name: "rocket", label: "Tên lửa" },
  { name: "ambulance", label: "Xe cứu thương" },
  { name: "tractor", label: "Máy kéo" },
  { name: "caravan", label: "Xe du lịch" },
  { name: "luggage", label: "Hành lý" },
  { name: "map-pinned", label: "Bản đồ địa điểm" },
  { name: "navigation", label: "Điều hướng" },
  { name: "compass", label: "La bàn" },
  { name: "cable-car", label: "Cáp treo" },
  { name: "tram", label: "Tàu điện" },
  { name: "plane-takeoff", label: "Máy bay cất cánh" },
  { name: "plane-landing", label: "Máy bay hạ cánh" },
  { name: "bus-basic", label: "Xe buýt thường" },
  { name: "taxi", label: "Taxi" },
  { name: "route", label: "Tuyến đường" },
  { name: "map-pin", label: "Địa điểm" },
  { name: "baggage", label: "Nhận hành lý" },
  { name: "armchair", label: "Ghế bành" },
  { name: "bath", label: "Phòng tắm" },
  { name: "bed-single", label: "Giường đơn" },
  { name: "door", label: "Cửa ra vào" },
  { name: "fence", label: "Hàng rào" },
  { name: "hammer", label: "Đóng sửa" },
  { name: "paint-roller", label: "Sơn nhà" },
  { name: "plug", label: "Ổ điện" },
  { name: "shower", label: "Vòi sen" },
  { name: "sofa", label: "Ghế sofa" },
  { name: "thermometer", label: "Nhiệt độ" },
  { name: "washing-machine", label: "Máy giặt" },
  { name: "microwave", label: "Lò vi sóng" },
  { name: "refrigerator", label: "Tủ lạnh" },
  { name: "lamp", label: "Đèn bàn" },
  { name: "fan", label: "Quạt" },
  { name: "key", label: "Chìa khoá" },
  { name: "warehouse", label: "Kho hàng" },
  { name: "utility-pole", label: "Điện dân dụng" },
  { name: "drill", label: "Khoan sửa chữa" },
  { name: "activity", label: "Hoạt động sức khoẻ" },
  { name: "bandage", label: "Băng cá nhân" },
  { name: "brain", label: "Tinh thần" },
  { name: "cross", label: "Y tế" },
  { name: "heart-handshake", label: "Chăm sóc" },
  { name: "pill", label: "Thuốc" },
  { name: "syringe", label: "Tiêm chủng" },
  { name: "test-tube", label: "Xét nghiệm" },
  { name: "accessibility", label: "Hỗ trợ tiếp cận" },
  { name: "glasses", label: "Kính mắt" },
  { name: "ear", label: "Tai mũi họng" },
  { name: "eye", label: "Mắt" },
  { name: "bone", label: "Xương khớp" },
  { name: "dna", label: "Di truyền" },
  { name: "microscope", label: "Nghiên cứu" },
  { name: "users", label: "Gia đình" },
  { name: "user", label: "Cá nhân" },
  { name: "heart-basic", label: "Yêu thích" },
  { name: "party", label: "Tiệc tùng" },
  { name: "smile", label: "Niềm vui" },
  { name: "hand-heart", label: "Từ thiện" },
  { name: "person", label: "Con người" },
  { name: "cake-basic", label: "Sinh nhật" },
  { name: "contact", label: "Liên hệ" },
  { name: "user-check", label: "Khách hàng" },
  { name: "book-marked", label: "Sách đã lưu" },
  { name: "book-check", label: "Học tập" },
  { name: "library", label: "Thư viện" },
  { name: "notebook", label: "Sổ ghi chép" },
  { name: "pen-tool", label: "Thiết kế" },
  { name: "pencil-ruler", label: "Kỹ thuật" },
  { name: "presentation", label: "Thuyết trình" },
  { name: "languages", label: "Ngoại ngữ" },
  { name: "flask", label: "Thí nghiệm" },
  { name: "clipboard", label: "Danh sách việc" },
  { name: "file-text", label: "Tài liệu" },
  { name: "badge-check", label: "Chứng nhận" },
  { name: "award", label: "Giải thưởng khác" },
  { name: "crown", label: "Cao cấp" },
]
